### registrar novo usuário - NÃO BARBEIRO
POST http://localhost:3001/usuario/registrar
Content-Type: application/json

{
    "nome": "Gabriel Pandolfo",
    "email": "gmpandolfo@empresa.com",
    "senha": "#Senha123",
    "telefone": "54999999999"
}
### autenticar usuário - NÃO BARBEIRO
POST http://localhost:3001/usuario/login
Content-Type: application/json

{
    "email": "gmpandolfo@empresa.com",
    "senha": "#Senha123"
}


### registrar novo usuário - BARBEIRO
POST http://localhost:3001/usuario/registrar
Content-Type: application/json

{
    "nome": "Paulo Tesourada",
    "email": "paulo@scissortitans.app",
    "senha": "#Senha123",
    "telefone": "54999999999",
    "barbeiro" : true
}
### autenticar usuário - BARBEIRO
POST http://localhost:3001/usuario/login
Content-Type: application/json

{
    "email": "paulo@scissortitans.app",
    "senha": "#Senha123"
}


### criar serviço - BARBEIRO
POST http://localhost:3001/servico
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywibm9tZSI6IlBhdWxvIFRlc291cmFkYSIsImVtYWlsIjoicGF1bG9Ac2Npc3NvcnRpdGFucy5hcHAiLCJ0ZWxlZm9uZSI6IjU0OTk5OTk5OTk5IiwiYmFyYmVpcm8iOnRydWUsImlhdCI6MTc0ODc1MTg4OSwiZXhwIjoxNzUwMDQ3ODg5fQ.oeSqPmYOQj_2hI4oKz_FJtu870aJ6ucc63o38-3XnH0
Content-Type: application/json

{
    "nome":"Barba Clássica",
    "descricao":"Barba aparada e estilizada",
    "preco":30,
    "qtdeSlots":3,
    "imagemURL":"http://example.com/barba.jpg"
}

### recuperar todos serviços
GET http://localhost:3001/servico

###
POST http://localhost:3001/agendamentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibm9tZSI6IkdhYnJpZWwgUGFuZG9sZm8iLCJlbWFpbCI6ImdtcGFuZG9sZm9AZW1wcmVzYS5jb20iLCJ0ZWxlZm9uZSI6IjU0OTk5OTk5OTk5IiwiYmFyYmVpcm8iOmZhbHNlLCJpYXQiOjE3NDg3NTA2NTQsImV4cCI6MTc1MDA0NjY1NH0.Qz8TB1gzkoKiRecCiwZ_B6mBVSw1G1YRLDBp9bRhsWQ
Content-Type: application/json

{
    "data": "2025-05-12T13:00:00.000Z",
    "usuario": { "id": 4 },
    "profissional": { "id": 3 },
    "servicos": [
        { "id": 1 }
    ]
}